"""Added the IADS_volume column in Subject model

Revision ID: 42119e68b17e
Revises: 7dbcb1055b96
Create Date: 2021-06-22 10:24:48.542722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42119e68b17e'
down_revision = '7dbcb1055b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('IADS_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'IADS_volume')
    # ### end Alembic commands ###
